# Generated by Django 4.1.5 on 2023-05-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo',
            options={'permissions': [('can_change_phone', 'Can change phone')]},
        ),
    ]
